project:
  type: website
website:
    title: "Austin Hoover"
    open-graph: False
    navbar:
        border: False
        right:
            - text: "Research"
              href: research.qmd
            - text: "Publications"
              href: publications.qmd
            - text: "Presentations"
              href: presentations.qmd
            - text: "Blog"
              href: blog.qmd
format:
    html:
        theme: 
            light: custom_light.scss
            dark: custom_dark.scss
        anchor-sections: true
        cap-location: margin
        toc-location: right
        title-block-categories: false
        shift-heading-level-by: 0
        